//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Seismic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Final_Seismic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (0,0,25)
        ///(0,1,25)
        ///(0,2,25)
        ///(0,3,25)
        ///(0,4,25)
        ///(0,5,25)
        ///(0,6,25)
        ///(0,7,25)
        ///(0,8,25)
        ///(0,9,25)
        ///(0,10,25)
        ///(0,11,25)
        ///(0,12,25)
        ///(0,13,25)
        ///(0,14,25)
        ///(0,15,25)
        ///(0,16,25)
        ///(0,17,25)
        ///(0,18,25)
        ///(0,19,25)
        ///(0,20,25)
        ///(0,21,25)
        ///(0,22,25)
        ///(0,23,25)
        ///(0,24,25)
        ///(0,25,25)
        ///(0,26,25)
        ///(0,27,25)
        ///(0,28,25)
        ///(0,29,25)
        ///(0,30,25)
        ///(0,31,25)
        ///(0,32,25)
        ///(0,33,25)
        ///(0,34,25)
        ///(0,35,25)
        ///(0,36,25)
        ///(0,37,25)
        ///(0,38,25)
        ///(0,39,25)
        ///(0,40,25)
        ///(0,41,25)
        ///(0,42,30)
        ///(0,43,30)
        ///(0,44,30)
        ///(0,45,30)
        ///(0,46,30)
        ///(0,47 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LeftImage {
            get {
                return ResourceManager.GetString("LeftImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (0,0,8)
        ///(0,1,8.18431154746157)
        ///(0,2,8.36862309492314)
        ///(0,3,8.55293464238471)
        ///(0,4,8.73724618984628)
        ///(0,5,8.92155773730785)
        ///(0,6,9.10586928476942)
        ///(0,7,9.29018083223098)
        ///(0,8,9.47449237969255)
        ///(0,9,9.65880392715412)
        ///(0,10,9.84311547461569)
        ///(0,11,10.0100712730287)
        ///(0,12,10.0777509471694)
        ///(0,13,10.14543062131)
        ///(0,14,10.2131102954506)
        ///(0,15,10.2807899695912)
        ///(0,16,10.3484696437318)
        ///(0,17,10.4161493178724)
        ///(0,18,10.4838289920131)
        ///(0,19,10.5515086661537)
        ///(0,20,10.6191883402943)
        ///(0,21,10.68686 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RightImage {
            get {
                return ResourceManager.GetString("RightImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SeismicImage1 {
            get {
                object obj = ResourceManager.GetObject("SeismicImage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SeismicImage2 {
            get {
                object obj = ResourceManager.GetObject("SeismicImage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
